#version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ncs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ncs_panda_dev
    ports:
      - "55432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

  backend:
    image: ncs_panda_backend_dev
    build:
      context: ..
      dockerfile: backend/Dockerfile
      target: no-cert
    working_dir: /app
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ../backend/src:/app/src
      - ../backend/prisma:/app/prisma
      - ../backend/tsconfig.json:/app/tsconfig.json
    env_file:
      - ../backend/.env
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: ncs_panda_frontend_dev
    build:
      context: ..
      dockerfile: frontend/Dockerfile
      target: no-cert
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend

volumes:
  db_data_dev:
